/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as FoundFriendsRouteImport } from './routes/found-friends'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PawFriendsIndexRouteImport } from './routes/paw-friends.index'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as PawFriendsSlugRouteImport } from './routes/paw-friends.$slug'
import { Route as FoundFriendsIdRouteImport } from './routes/found-friends.$id'
import { Route as ExploreNatureRouteImport } from './routes/explore.nature'
import { Route as ExploreMapRouteImport } from './routes/explore.map'
import { Route as ExploreDiaryRouteImport } from './routes/explore.diary'
import { Route as ExploreAiRouteImport } from './routes/explore.ai'
import { Route as AuthenticatedPetStudioRouteImport } from './routes/_authenticated/pet-studio'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundFriendsRoute = FoundFriendsRouteImport.update({
  id: '/found-friends',
  path: '/found-friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PawFriendsIndexRoute = PawFriendsIndexRouteImport.update({
  id: '/paw-friends/',
  path: '/paw-friends/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExploreRoute,
} as any)
const PawFriendsSlugRoute = PawFriendsSlugRouteImport.update({
  id: '/paw-friends/$slug',
  path: '/paw-friends/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundFriendsIdRoute = FoundFriendsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FoundFriendsRoute,
} as any)
const ExploreNatureRoute = ExploreNatureRouteImport.update({
  id: '/nature',
  path: '/nature',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreMapRoute = ExploreMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreDiaryRoute = ExploreDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreAiRoute = ExploreAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => ExploreRoute,
} as any)
const AuthenticatedPetStudioRoute = AuthenticatedPetStudioRouteImport.update({
  id: '/pet-studio',
  path: '/pet-studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/admin/moderation',
    path: '/admin/moderation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRouteWithChildren
  '/found-friends': typeof FoundFriendsRouteWithChildren
  '/garden': typeof GardenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/pet-studio': typeof AuthenticatedPetStudioRoute
  '/explore/ai': typeof ExploreAiRoute
  '/explore/diary': typeof ExploreDiaryRoute
  '/explore/map': typeof ExploreMapRoute
  '/explore/nature': typeof ExploreNatureRoute
  '/found-friends/$id': typeof FoundFriendsIdRoute
  '/paw-friends/$slug': typeof PawFriendsSlugRoute
  '/explore/': typeof ExploreIndexRoute
  '/paw-friends/': typeof PawFriendsIndexRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/found-friends': typeof FoundFriendsRouteWithChildren
  '/garden': typeof GardenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/pet-studio': typeof AuthenticatedPetStudioRoute
  '/explore/ai': typeof ExploreAiRoute
  '/explore/diary': typeof ExploreDiaryRoute
  '/explore/map': typeof ExploreMapRoute
  '/explore/nature': typeof ExploreNatureRoute
  '/found-friends/$id': typeof FoundFriendsIdRoute
  '/paw-friends/$slug': typeof PawFriendsSlugRoute
  '/explore': typeof ExploreIndexRoute
  '/paw-friends': typeof PawFriendsIndexRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRouteWithChildren
  '/found-friends': typeof FoundFriendsRouteWithChildren
  '/garden': typeof GardenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/_authenticated/pet-studio': typeof AuthenticatedPetStudioRoute
  '/explore/ai': typeof ExploreAiRoute
  '/explore/diary': typeof ExploreDiaryRoute
  '/explore/map': typeof ExploreMapRoute
  '/explore/nature': typeof ExploreNatureRoute
  '/found-friends/$id': typeof FoundFriendsIdRoute
  '/paw-friends/$slug': typeof PawFriendsSlugRoute
  '/explore/': typeof ExploreIndexRoute
  '/paw-friends/': typeof PawFriendsIndexRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/explore'
    | '/found-friends'
    | '/garden'
    | '/sitemap.xml'
    | '/stories'
    | '/pet-studio'
    | '/explore/ai'
    | '/explore/diary'
    | '/explore/map'
    | '/explore/nature'
    | '/found-friends/$id'
    | '/paw-friends/$slug'
    | '/explore/'
    | '/paw-friends/'
    | '/admin/moderation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/found-friends'
    | '/garden'
    | '/sitemap.xml'
    | '/stories'
    | '/pet-studio'
    | '/explore/ai'
    | '/explore/diary'
    | '/explore/map'
    | '/explore/nature'
    | '/found-friends/$id'
    | '/paw-friends/$slug'
    | '/explore'
    | '/paw-friends'
    | '/admin/moderation'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/explore'
    | '/found-friends'
    | '/garden'
    | '/sitemap.xml'
    | '/stories'
    | '/_authenticated/pet-studio'
    | '/explore/ai'
    | '/explore/diary'
    | '/explore/map'
    | '/explore/nature'
    | '/found-friends/$id'
    | '/paw-friends/$slug'
    | '/explore/'
    | '/paw-friends/'
    | '/_authenticated/admin/moderation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  FoundFriendsRoute: typeof FoundFriendsRouteWithChildren
  GardenRoute: typeof GardenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRoute
  PawFriendsSlugRoute: typeof PawFriendsSlugRoute
  PawFriendsIndexRoute: typeof PawFriendsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found-friends': {
      id: '/found-friends'
      path: '/found-friends'
      fullPath: '/found-friends'
      preLoaderRoute: typeof FoundFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paw-friends/': {
      id: '/paw-friends/'
      path: '/paw-friends'
      fullPath: '/paw-friends/'
      preLoaderRoute: typeof PawFriendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/paw-friends/$slug': {
      id: '/paw-friends/$slug'
      path: '/paw-friends/$slug'
      fullPath: '/paw-friends/$slug'
      preLoaderRoute: typeof PawFriendsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found-friends/$id': {
      id: '/found-friends/$id'
      path: '/$id'
      fullPath: '/found-friends/$id'
      preLoaderRoute: typeof FoundFriendsIdRouteImport
      parentRoute: typeof FoundFriendsRoute
    }
    '/explore/nature': {
      id: '/explore/nature'
      path: '/nature'
      fullPath: '/explore/nature'
      preLoaderRoute: typeof ExploreNatureRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/map': {
      id: '/explore/map'
      path: '/map'
      fullPath: '/explore/map'
      preLoaderRoute: typeof ExploreMapRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/diary': {
      id: '/explore/diary'
      path: '/diary'
      fullPath: '/explore/diary'
      preLoaderRoute: typeof ExploreDiaryRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/ai': {
      id: '/explore/ai'
      path: '/ai'
      fullPath: '/explore/ai'
      preLoaderRoute: typeof ExploreAiRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_authenticated/pet-studio': {
      id: '/_authenticated/pet-studio'
      path: '/pet-studio'
      fullPath: '/pet-studio'
      preLoaderRoute: typeof AuthenticatedPetStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPetStudioRoute: typeof AuthenticatedPetStudioRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPetStudioRoute: AuthenticatedPetStudioRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ExploreRouteChildren {
  ExploreAiRoute: typeof ExploreAiRoute
  ExploreDiaryRoute: typeof ExploreDiaryRoute
  ExploreMapRoute: typeof ExploreMapRoute
  ExploreNatureRoute: typeof ExploreNatureRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreAiRoute: ExploreAiRoute,
  ExploreDiaryRoute: ExploreDiaryRoute,
  ExploreMapRoute: ExploreMapRoute,
  ExploreNatureRoute: ExploreNatureRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface FoundFriendsRouteChildren {
  FoundFriendsIdRoute: typeof FoundFriendsIdRoute
}

const FoundFriendsRouteChildren: FoundFriendsRouteChildren = {
  FoundFriendsIdRoute: FoundFriendsIdRoute,
}

const FoundFriendsRouteWithChildren = FoundFriendsRoute._addFileChildren(
  FoundFriendsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRouteWithChildren,
  FoundFriendsRoute: FoundFriendsRouteWithChildren,
  GardenRoute: GardenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRoute,
  PawFriendsSlugRoute: PawFriendsSlugRoute,
  PawFriendsIndexRoute: PawFriendsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
